apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: serviceone
  annotations:
    kubernetes.io/change-cause: "ServiceOne Deployment"
  name: serviceone
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: serviceone
  template:
    metadata:
      labels:
        app: serviceone
    spec:
      containers:
      - image: 10.0.0.4:8085/zong-01/svc1:v5.0.0.2-64-77bb4d1
        name: sone
       # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Karachi
#      imagePullSecrets:
#        - name: myregkey
---
apiVersion: v1
kind: Service
metadata:
  name: serviceone
  labels:
    app: serviceone
spec:
  selector:
    app: serviceone
  type: NodePort
  ports:
  - name: serviceone
    port: 80
    protocol: TCP
    targetPort: 5001
    nodePort: 30071
