---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp-vs
  namespace: myapp
spec:
  hosts:
  - hi.aksa.com.pk
  gateways:
  - myapp-gateway
  http:
  - route:
    - destination:
        host: webserver
        port:
          number: 80
